#!/bin/bash

# Prohibit *, ? file expansion 
set -o noglob

DIR='./'
FILE='*.h'
if (($# == 3)); then
    DIR=$1
    FILE=$2
    CLASS=$3
elif (($# == 2)); then
    FILE=$1
    CLASS=$2
elif (($# == 1)); then
    CLASS=$1
elif (($# == 0)); then
    echo -e " 
Search directory for class or struct.

USAGE: $(basename $0) [dir] [file_pattern] <class_pattern>
    dir\t\t\t Directory to search. ./ if omitted.
    file_pattern\t Source file to search, can be '*.h|*.cpp'. *.h if omitted.
    class_pattern\t Symbol of class or struct to search
"
    exit 1
fi

FILE=$(echo $FILE |expand_find_pat)

GREP_RE="\(class\|struct\)[[:space:]]\+\([[:alnum:]_]\+[[:space:]]\+\)\?${CLASS}[[:space:]]*\([:{]\|$\)"


OUTPUT=$(find $DIR $FILE | xargs grep $GREP_RE -n)
if [ $OUTPUT == "" ]; then
    exit 0
fi

# Change line form for vi input, and highlight the file path, line and class of grep
echo "$OUTPUT" | gawk -v class=$CLASS -F: \
    'BEGIN{\
        classrep="\\<"class"\\>"; \
        red="\033[0;31m"; \
        green="\033[0;32m"; \
        blue="\033[0;34m"; \
        white="\033[0;37m"\
    } \
    {\
        for(i=3;i<=NF;i++)\
            {line=file$i} \
        gsub(classrep,red class white, line); \
        print green $1 blue " +" $2 white" : "line\
    }'

tput sgr0
