#!/bin/bash

# Prohibit *, ? file expansion 
set -o noglob

PROG_DIR=$(dirname $(readlink -f $0))

DIR='./'
FILE='*.h|*.hpp'
if (($# == 3)); then
    DIR=$1
    FILE=$2
    CLASS=$3
elif (($# == 2)); then
    FILE=$1
    CLASS=$2
elif (($# == 1)); then
    CLASS=$1
elif (($# == 0)); then
    echo -e " 
Search directory for class or struct.

USAGE: $(basename $0) [dir] [file_pattern] <class_pattern>
    dir\t\t\t Directory to search. ./ if omitted.
    file_pattern\t Source file to search, can be '*.h|*.cpp'. *.h if omitted.
    class_pattern\t Symbol of class or struct to search
"
    exit 1
fi

FILE=$(echo $FILE |expand_find_pat)

GREP_RE="\(class\|struct\)[[:space:]]\+\([[:alnum:]_]\+[[:space:]]\+\)\?${CLASS}[[:space:]]*\([:{]\|$\)"

 
#echo "find $DIR $FILE | xargs grep $GREP_RE -n -H"
OUTPUT=$(find $DIR $FILE | xargs grep $GREP_RE -n -H)
if [ "X${OUTPUT}" == "X" ]; then
    exit 0
fi

#echo $OUTPUT
# Change line form for vi input, and highlight the file path, line and class of grep
echo "$OUTPUT" | gawk -v symbol=$CLASS -f ${PROG_DIR}/grep_highlight
tput sgr0
