#!/bin/bash

set -o noglob
DIR='./'
FILE='*.h'
if (($# == 3)); then
    DIR=$1
    FILE=$2
    CLASS=$3
elif (($# == 2)); then
    FILE=$1
    CLASS=$2
elif (($# == 1)); then
    CLASS=$1
elif (($# == 0)); then
    echo USAGE: $0 "[dir] [file_pattern] <class_pattern>"
    exit 1
fi


#echo $DIR
#echo $FILE
#echo $CLASS

FILE=$(echo $FILE |gawk -F'|' '{file="-name "$1" -print"; for(i=2;i<=NF;i++) {file=file" -or -name "$i" -print";}} END{print file}')

#echo $FILE
#exit
GREP_RE="\(class\|struct\)[[:space:]]\+\([[:alnum:]_]\+[[:space:]]\+\)\?${CLASS}[[:space:]]*\([:{]\|$\)"
#echo $GREP_RE
#exit

#echo "find $DIR $FILE |xargs grep $GREP_RE -n --color |sed 's/:/ +/'"
#OUTPUT=$(find $DIR $FILE |xargs grep $GREP_RE -n |sed 's/:/ +/; s/^\([^:]\+\)/\\\\e[0;32m\1\\\\e[0;37m/')
#OUTPUT=$(find $DIR $FILE |xargs grep $GREP_RE)
find $DIR $FILE |xargs grep $GREP_RE -n | gawk -v class=$CLASS -F: 'BEGIN{classrep="\\<"class"\\>"} {for(i=3;i<=NF;i++){line=file$i} gsub(classrep,"\033[0;31m"class"\033[0;37m",line); print "\033[0;32m"$1"\033[0;34m +"$2"\033[0;37m: "line}'
#find $DIR $FILE |xargs grep $GREP_RE -n --color | sed 's/:/ +/'
#
#if [ OUTPUT == "" ]; then
#    exit 0
#fi
#
#FILE_INFO=$(echo $OUTPUT |sed "s/^\([^:]*\)/\\\\e[0;32m\1\\\\e[0;37m/")
#
#
#printf  "%b\n" "$OUTPUT"
#echo -e $OUTPUT
tput sgr0
